### ISSUE TITLE
[Feature] Integrate Voice Interaction

### ISSUE THREAD

**Issue by aj47** [aj47/clickolas-cage#7]

**Comment by Shiv282** [comment]
Hey @aj47,
Is this issue still open?
We can use `webkitSpeechRecognition` for the speech to text and I wasn't able to perform the same on the extension level, so scripting this in the active tab and receiving a POST message from there back to extension, have tried this out and works as expected. Do let me know if you find this useful

**Comment by aj47** [comment]
> Hey @aj47, Is this issue still open? We can use `webkitSpeechRecognition` for the speech to text and I wasn't able to perform the same on the extension level, so scripting this in the active tab and receiving a POST message from there back to extension, have tried this out and works as expected. Do let me know if you find this useful

Yes @Shiv282 ! That would be great to have the STT done locally with webkit.

**Comment by aj47** [comment]
https://github.com/KoljaB/RealtimeSTT this is good

**Comment by aj47** [comment]
Implemented in latest commit
