### ISSUE TITLE
[BUG] - Hide the static element when it completes the task

### ISSUE THREAD

**Issue by anonfaded** [aj47/clickolas-cage#9]
## Issue description
Right now when it completes the task like here opening youtube and searching for something, we get this static element on the screen which doesn't move with scrolling.

![image](https://github.com/aj47/clickolas-cage/assets/124708903/bed42ba9-3e68-411b-a311-a954c0227f15)

## To-do

- [ ] Implement a feature so we don't get the element on screen which is `(Thinking...)`. Maybe hide it from css property or anything.

**Comment by Shiv282** [comment]
Hey team,
How about we implement a Close button in the Side Panel and we let the user close the Side Panel when he feels it is not needed?

**Comment by anonfaded** [comment]
> Hey team, How about we implement a Close button in the Side Panel and we let the user close the Side Panel when he feels it is not needed?

but its an extension thing so how can sidepanel be implimented? anyways lets see if you can try  something to fix it

**Comment by aj47** [comment]
> Hey team, How about we implement a Close button in the Side Panel and we let the user close the Side Panel when he feels it is not needed?

yes i think this is a good idea

**Comment by Shiv282** [comment]
I have added a snapshot of how it might look, can you let me know if this is something we can do?

PS : Close button can be made better

![Uploading Screenshot 2024-06-01 at 1.25.51 AM.png…]()

**Comment by aj47** [comment]
great start @Shiv282 ! don't worry too much about making it look good, we will probably do a big UI overhaul eventually. first lets get it working. maybe a floating button to open the panel back would be good.

**Comment by aj47** [comment]
@Shiv282  Let me know if you have an update on progress, feel free to commit and PR what you have so far, i'll have a look.

**Comment by aj47** [comment]
no longer an issue with new UI
